config/routes.rb
RailsBestpracticesCom::Application.routes.draw do |map|
  Typus::Routes.draw(map)

  match "/tags/:name", :to => "posts#index"
  resources :tags, :only => :show do
    resources :posts, :only => :index
  end
  resources :posts do
    get :archive, :on => :collection
    get :search, :on => :collection
    resources :comments, :only => :create
    resources :votes, :only => [:create, :destroy]
    resources :implementation, :only => [:show, :new, :create, :edit, :update]
  end
  resources :implementations do
    resources :comments, :only => :create
  end

  resources :users, :only => [:new, :create, :edit, :update]

  resource :user_session
  
  match 'page/:name' => 'pages#show', :as => :page

  root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Markdownable
  acts_as_taggable
  
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  has_one :implementation, :dependent => :destroy
  
  validates_presence_of :title, :body
  validates_uniqueness_of :title
  
  default_scope order('created_at desc')
  with_exclusive_scope do
    scope :hot, order('vote_points desc').limit(20)
  end
  
  def self.per_page
    10
  end
  
  def belongs_to?(user)
    user && user_id == user.id
  end

  def vote(user)
    self.votes.where(:user_id => user.id).first
  end
  
  def to_param
    return "#{id}-#{title.parameterize}"
  end
end

app/controllers/admin/posts_controller.rb
# Controller generated by Typus, use it to extend admin functionality.
class Admin::PostsController < Admin::ResourcesController

end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_filter :require_user, :only => [:new, :edit, :create, :update, :destroy]
  belongs_to :tag, :optional => true, :class_name => 'ActsAsTaggableOn::Tag',
    :finder => :find_by_name!, :param => :name
  has_scope :hot
  respond_to :xml, :atom, :only => :index

  show! do |format|
    @post.increment!(:view_count)
  end
  
  def archive
    @posts = Post.all
  end
  
  def search
    @posts = Post.where(['title like ?', "%#{params[:q]}%"]).paginate(:page => params[:page])
    render :action => :index
  end
  
  protected
    def begin_of_association_chain
      @current_user
    end
    
    def collection
      @posts ||= end_of_association_chain.paginate(:page => params[:page])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= f.inputs do
  = f.input :title, :label => 'Title'
  = f.input :description, :label => 'Short Description', :hint => 'Please give a short description about this best practices', :input_html => { :class => 'wmd-ignore', :rows => 6 }
  = f.input :tag_list, :hint => 'Split by comma ( , )'
  = f.input :body, :label => 'Content'
  .wmd-preview.wikistyle

:javascript
  var tags = #{all_tags};
  wmd_options = {"output": "Markdown"};
= javascript_include_tag 'wmd'

app/views/posts/archive.html.haml
%h2 All Rails Best Practices
.posts.archive
  - @posts.each do |post|
    .post
      .title= link_to post.title, post_path(post)

app/views/posts/edit.html.haml
%h2 Edit a Rails Best Practice

= semantic_form_for @post do |form|
  = render 'form', :f => form
  = form.buttons do
    = form.submit "Save"
    = link_to 'Back', post_path(@post)

app/views/posts/index.html.haml
%h2 Rails Best Practices
.posts
  - @posts.each do |post|
    .post
      = image_tag post.user.gravatar_url(:size => 32), :class => 'user-avatar'
      %span.title= link_to post.title, post_path(post)
      %span.description= post.description
      %p
        by
        = user_link(post.user)
        &nbsp;|&nbsp;
        = "#{post.vote_points} votes"
        &nbsp;|&nbsp;
        = link_to (post.comments.size == 0 ? "post a comment" : "#{post.comments.size} comments"), post_path(post, :anchor => 'comments')
= will_paginate @posts, :previous_label => "<< Newer", :next_label => "Older >>"

app/views/posts/new.html.haml
%h2 Share a Rails Best Practice

= semantic_form_for @post do |form|
  = render 'form', :f => form
  = form.buttons do
    = form.submit "Create"
    = link_to 'Back', posts_path

app/views/posts/show.html.haml
%h2= @post.title

.post
  - if @post.belongs_to? current_user
    .command
      = link_to 'Edit', edit_post_path(@post)
      - if current_user and current_user.developer?
        &nbsp;|&nbsp;
        - if @post.implementation
          = link_to 'Edit Implementation', edit_post_implementation_path(@post, @post.implementation)
        - else
          = link_to 'New Implement', new_post_implementation_path(@post)
  .vote-info
    = vote_like_link(@post)
    %p= @post.vote_points
    = vote_unlike_link(@post)
  %p
    Posted by 
    = image_tag @post.user.gravatar_url(:size => 16), :class => 'user-avatar'
    = user_link(@post.user)
    on 
    = @post.created_at.to_date.strftime("%B %d, %Y")
  %p
    = render 'shared/add_this_link'
  %p
    %strong Short Description: 
    = @post.description
  .wikistyle= raw @post.formatted_html
  - if @post.implementation
    = link_to 'Implemented in rails_best_practices gem', post_implementation_path(@post, @post.implementation), :class => 'implemented'
  .tags
    %strong tags: 
    - @post.tags.each do |tag|
      = link_to tag.name, tag_path(tag.name)

  = render 'comments/comments', :parent => @post
  = render 'comments/comment_form', :parent => @post

= render 'shared/add_this_script'