config/routes.rb
RailsBestpracticesCom::Application.routes.draw do |map|
  Typus::Routes.draw(map)

  match "/tags/:name", :to => "posts#index"
  resources :tags, :only => :show do
    resources :posts, :only => :index
  end
  resources :posts do
    get :archive, :on => :collection
    get :search, :on => :collection
    resources :comments, :only => :create
    resources :votes, :only => [:create, :destroy]
    resources :implementation, :only => [:show, :new, :create, :edit, :update]
  end
  resources :implementations do
    resources :comments, :only => :create
  end

  resources :users, :only => [:new, :create, :edit, :update]

  resource :user_session
  
  match 'page/:name' => 'pages#show', :as => :page

  root :to => "posts#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

  ROLE = Typus::Configuration.roles.keys.sort
  LANGUAGE = Typus.locales

  enable_as_typus_user

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true, :counter_cache => true
  belongs_to :user

  validates_presence_of :body
  validates_presence_of :username, :if => Proc.new { |comment| !comment.user_id }
end

app/models/implementation.rb
class Implementation < ActiveRecord::Base
  include Markdownable

  belongs_to :user
  belongs_to :post
  has_many :comments, :as => :commentable, :dependent => :destroy
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates_presence_of :name
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Markdownable
  acts_as_taggable
  
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  has_one :implementation, :dependent => :destroy
  
  validates_presence_of :title, :body
  validates_uniqueness_of :title
  
  default_scope order('created_at desc')
  with_exclusive_scope do
    scope :hot, order('vote_points desc').limit(20)
  end
  
  def self.per_page
    10
  end
  
  def belongs_to?(user)
    user && user_id == user.id
  end

  def vote(user)
    self.votes.where(:user_id => user.id).first
  end
  
  def to_param
    return "#{id}-#{title.parameterize}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  is_gravtastic!
  
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  has_many :implementations, :dependent => :destroy
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  after_create :update_create_vote
  before_destroy :update_destroy_vote

  private
    def update_create_vote
      if like?
        post.increment!(:vote_points)
      else
        post.decrement!(:vote_points)
      end
    end

    def update_destroy_vote
      if like?
        post.decrement!(:vote_points)
      else
        post.increment!(:vote_points)
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by_name(params[:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_filter :require_user, :only => [:new, :edit, :create, :update, :destroy]
  belongs_to :tag, :optional => true, :class_name => 'ActsAsTaggableOn::Tag',
    :finder => :find_by_name!, :param => :name
  has_scope :hot
  respond_to :xml, :atom, :only => :index

  show! do |format|
    @post.increment!(:view_count)
  end
  
  def archive
    @posts = Post.all
  end
  
  def search
    @posts = Post.where(['title like ?', "%#{params[:q]}%"]).paginate(:page => params[:page])
    render :action => :index
  end
  
  protected
    def begin_of_association_chain
      @current_user
    end
    
    def collection
      @posts ||= end_of_association_chain.paginate(:page => params[:page])
    end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  actions :new, :create, :edit, :update
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  create! do |success, failure|
    success.html { redirect_to root_url }
    failure.html { render :action => :new }
  end
  
  update! do |success, failure|
    success.html { redirect_to root_url }
    failure.html { render :action => :edit }
  end

private
  def resource
    @user = @current_user
  end
end

app/controllers/votes_controller.rb
class VotesController < InheritedResources::Base
  before_filter :require_user
  actions :create, :destroy
  belongs_to :post

  def create
    @post = Post.find(params[:post_id])
    @vote = @post.votes.create(:user_id => current_user.id, :like => like_value)
    create! do |format|
      format.html { redirect_to post_path(@post) }
    end
  end

  destroy! do |format|
    format.html { redirect_to post_path(@post) }
  end

  private
    def like_value
      params[:like] == "true" ? true : false
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_user_link(comment)
    if comment.user and comment.user.url
      link_to comment.user.login, comment.user.url, :target => '_blank'
    elsif comment.user
      comment.user.login
    else
      comment.username
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  def all_tags
    "[#{ ActsAsTaggableOn::Tag.all.collect{|t| "'#{t.name}'"}.join(",") }]"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_link(user)
    if user.url
      link_to user.login, user.url, :target => '_blank'
    else
      content_tag :span, user.login
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def vote_like_link(post)
    unless current_user
      return link_to_function('Like', "alert('You should log in before vote!')", :class => 'like-icon')
    end
    vote = post.vote current_user
    if vote
      if vote.like?
        link_to 'Like', '#', :class => 'like-icon active'
      else
        button_to 'Like', post_vote_path(post, vote), :method => :delete, :class => 'like-icon'
      end
    else
      button_to 'Like', post_votes_path(@post, :like => true), :class => 'like-icon'
    end
  end
  
  def vote_unlike_link(post)
    unless current_user
      return link_to_function('Unlike', "alert('You should log in before vote!')", :class => 'unlike-icon')
    end
    vote = post.vote current_user
    if vote
      if vote.like?
        button_to 'Unlike', post_vote_path(post, vote), :method => :delete, :class => 'unlike-icon'
      else
        link_to 'Unlike', '#', :class => 'unlike-icon active'
      end
    else
      button_to 'Unlike', post_votes_path(@post, :like => false), :class => 'unlike-icon'
    end
  end
end

app/views/admin/pages/_edit.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag "ckeditor/ckeditor" %>
  <script type="text/javascript">
    $(function() {
      if ($('textarea').length > 0) {
        var data = $('textarea');
        $.each(data, function(i) { CKEDITOR.replace(data[i].id); });
      }
    });
  </script>
<% end %>

app/views/admin/pages/_new.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag "ckeditor/ckeditor" %>
  <script type="text/javascript">
    $(function() {
      if ($('textarea').length > 0) {
        var data = $('textarea');
        $.each(data, function(i) { CKEDITOR.replace(data[i].id); });
      }
    });
  </script>
<% end %>

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml", "xml:lang" => "en", :lang => "en"}
  %head
    %title rails-bestpractices.com
    = stylesheet_link_tag 'compiled/screen', 'compiled/layout', 'compiled/post', 'compiled/implementation', 'compiled/comment', 'compiled/jquery.autocomplete', 'compiled/formtastic', 'compiled/formtastic_changes', 'compiled/css_sprite', :cache => true, :media => 'screen, projection'
    = stylesheet_link_tag 'compiled/print.css', :media => 'print'
    /[if IE]
      = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
    = auto_discovery_link_tag(:atom, posts_path(:format => 'atom'))
    = auto_discovery_link_tag(:rss, posts_path(:format => 'xml'))
    = csrf_meta_tag
  %body.bp.two-col
    #container
      #header
        .logo
          %h1 Rails Best Practices
          %p Follow The Rails Best Practices Here
          %p Share Your Rails Best Practices Here
        .nav
          %ul
            %li= link_to "Home", root_path
            - if !current_user
              %li= link_to "Register", new_user_path
              %li= link_to "Login", new_user_session_path
            - else
              %li= link_to 'Submit', new_post_path, :class => 'highlight'
              %li= link_to current_user.login, edit_user_path(current_user)
              %li= link_to "Logout", user_session_path, :method => :delete, :confirm => "Are you want to logout?"
            %li= link_to "About", page_path(:name => 'about-us')
          = form_tag search_posts_path, :method => :get do
            = label_tag 'Search'
            = text_field_tag 'q'

      .flash
        - flash.each do |type, message|
          .message{:class => type}= message
      #sidebar
        .section
          %h3 Navigation
          %ul
            %li= link_to 'Recent Best Practices', posts_url
            %li= link_to 'Hot Best Practices', posts_url(:hot => true)
            %li= link_to 'All Best Practices', archive_posts_url
        .section
          %h3 Tags
          %ul
            - ActsAsTaggableOn::Tag.order("name").each do |tag|
              %li= link_to tag.name, tag_path(tag.name)
      #content
        = yield
      #footer
      
    = javascript_include_tag :defaults
    = javascript_include_tag 'jquery.autocomplete'
    :javascript
      $(function() {
        // tag list auto complete
        if (typeof tags != 'undefined') {
          $('#post_tag_list').autocomplete(tags, {
        		multiple: true,
        		matchContains: true,
        		autoFill: true
        	});
        }
        // remove the beginning spaces in <pre><code> </code></pre>
        $.each($('pre code'), function(i, element) {
          var output = [];
          $.each($(element).text().split('\n'), function(i, line) {
            output.push(line.replace(/^ {12}/, ''));
          });
          $(element).text(output.join('\n'));
        });
      });

app/views/pages/show.html.haml
.page
  - if @page
    .wikistyle= raw @page.body
  - else
    Nothing